# Site settings
title: Adventures In Coding Later In Life
header-img: img/home-bg.png
email: jhardrick68@outlook.com
copyright_name: Jhardrick
description: > # this means to ignore newlines until "baseurl:"
  Coding While Female
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Jhardrick
learn_profile: Jhardrick
email_username: jhardrick68@outlook.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
